---
- name: Provisioning Server
  hosts: all
  become: yes
  tasks:
    - name: Install NTP
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Install NTP in the ubuntu
      apt:
        name: ntp"{{item}}"
        state: present
        update_cache: yes
      when: ansibel_distribution == "Ubuntu"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip


    - name: Start and enable NTP on redhat
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_os_family == "Redhat"

    - name: Start and enable NTP on Debian
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"
      
